# Generated by Django 3.2.2 on 2021-05-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_time_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.item', verbose_name='Задача'),
        ),
    ]
